default: &default
  adapter: postgresql
  username: tracker
  password: aaa111
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tracker_development

test:
  <<: *default
  database: tracker_test

production:
  <<: *default
  database: tracker_production
